--- #YAML:1.0
name:                Data-DublinCore
version:             0.04
abstract:            DublinCore XML schemas
license:             perl
author:              
    - Mark Overmeer
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Log::Report:                   0.23
    Test::More:                    0.54
    Test::Pod:                     1.00
    XML::Compile:                  1.15
    XML::Compile::Cache:           0.92
    XML::LibXML::Simple:           0.13
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
