--- #YAML:1.0
name:               Data-DublinCore
version:            0.01
abstract:           DublinCore XML schemas
author:
    - Mark Overmeer
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Log::Report:          0.23
    Test::More:           0.54
    Test::Pod:            1.00
    XML::Compile:         1.07
    XML::Compile::Cache:  0.92
    XML::LibXML::Simple:  0.13
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.52
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
